services:
  api_tests_for_test_2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/Test_2
    command: /bin/sh -c "pytest Moneybox/tests/Get_all_moneybox -sv --alluredir=allure-results"
    working_dir: /Test_2
#
#  report:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/Test
#    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
#    working_dir: /Test